export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const FETCH_PURCHASES = "FETCH_PURCHASES";
export const SET_SELECTED_CUSTOMER = "SET_SELECTED_CUSTOMER";